# Generated by Django 3.0.8 on 2020-08-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=30, unique=True, verbose_name='Serial Number')),
                ('imei', models.CharField(max_length=50, unique=True, verbose_name='IMEI Number')),
                ('part_no', models.CharField(max_length=30, verbose_name='Part Number')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('model', models.CharField(max_length=40, verbose_name='Model')),
                ('screen_size', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Screen Size')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('is_emi', models.BooleanField(default=False, verbose_name='Is EMI?')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Is Blocked?')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date/Time')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Date/Time Modified')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'unique_together': {('serial_no', 'imei')},
            },
        ),
    ]
