# Generated by Django 3.0.8 on 2020-08-22 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('serial_no', 'part_no')},
        ),
        migrations.RemoveField(
            model_name='product',
            name='imei',
        ),
    ]
