# Generated by Django 3.0.8 on 2020-09-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200822_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='screen_size',
            field=models.CharField(max_length=50, verbose_name='Screen Size'),
        ),
    ]
