# Generated by Django 3.0.8 on 2020-08-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_token', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='title',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Title'),
        ),
    ]
