# Generated by Django 3.0.8 on 2022-03-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostSaleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=60, null=True, verbose_name='Customer Name')),
                ('customer_email', models.CharField(max_length=60, null=True, verbose_name='Customer Email')),
                ('customer_mobile_no', models.CharField(max_length=12, null=True, verbose_name='Mobile Number')),
                ('product_name', models.CharField(max_length=60, null=True, verbose_name='Product Name / Code')),
                ('assetMake', models.CharField(max_length=60, verbose_name='Asset Make')),
                ('assetModel', models.CharField(max_length=60, verbose_name='Asset Model')),
                ('serialNo', models.CharField(max_length=60, verbose_name='Serial No')),
                ('invoiceDate', models.CharField(max_length=60, verbose_name='Invoice Date')),
                ('invoiceValue', models.CharField(max_length=60, verbose_name='Invoice Value')),
                ('customer_address', models.CharField(max_length=60, verbose_name='Customer Address')),
                ('pin_code', models.CharField(max_length=6, verbose_name='Customer Pin code')),
                ('city', models.CharField(max_length=20, verbose_name='City')),
                ('state', models.CharField(max_length=15, verbose_name='State')),
                ('OA_Plan_name', models.CharField(max_length=60, verbose_name='One Assist Plan name')),
                ('OA_plan_price_paid_by_seller', models.CharField(max_length=60, verbose_name='One Assist plan price paid by seller')),
                ('OA_plan_price_to_customer', models.CharField(max_length=60, verbose_name='One Assist plan price to customer')),
                ('partner_name', models.CharField(max_length=60, verbose_name='Partner Name')),
                ('partner_bu_name', models.CharField(max_length=60, verbose_name='Partner bu name')),
                ('MembershipId', models.CharField(max_length=60, verbose_name='MembershipId')),
                ('primary_customerID', models.CharField(max_length=60, verbose_name='Primary Customer ID')),
                ('start_date', models.DateField(max_length=60, verbose_name='Start date')),
                ('end_date', models.DateField(max_length=60, verbose_name='End date')),
            ],
            options={
                'verbose_name': 'Post Sale Data',
                'verbose_name_plural': 'Post Sales Data',
            },
        ),
    ]
