# Generated by Django 3.0.8 on 2022-03-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postsale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsalemodel',
            name='end_date',
            field=models.DateField(verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='postsalemodel',
            name='start_date',
            field=models.DateField(verbose_name='Start date'),
        ),
    ]
